server:
  port: 8082
spring:
  data:
    mongodb:
      host: localhost
      name: embeded_db
  application:
    name: po
logging:
  level:
    org:
      nipu: DEBUG
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka/
